"""CAD/BIM file import via DDC Community converters.

Workflow:
1. User uploads .rvt/.ifc/.dwg/.dgn file
2. Backend saves to temp dir
3. Runs appropriate DDC converter (.exe) -> produces Excel
4. Parses Excel -> extracts elements (type, volume, area, count)
5. AI maps elements to construction work items with pricing
6. Returns BOQ positions ready for import
"""

import asyncio
import logging
import os
from pathlib import Path

logger = logging.getLogger(__name__)

# Converter mapping: file extension -> converter executable name
CONVERTERS: dict[str, str] = {
    "rvt": "RvtExporter.exe",
    "ifc": "IfcExporter.exe",
    "dwg": "DwgExporter.exe",
    "dgn": "DgnExporter.exe",
}

SUPPORTED_CAD_EXTENSIONS: set[str] = set(CONVERTERS.keys())

# Look for converters in these locations (in order)
CONVERTER_SEARCH_PATHS: list[Path] = [
    Path("converters/bin"),
    Path.home() / ".openestimator" / "converters",
    Path("/opt/openestimator/converters"),
    Path("C:/ProgramData/OpenEstimator/converters"),
]


def find_converter(extension: str) -> Path | None:
    """Find the converter executable for a given file extension.

    Searches through ``CONVERTER_SEARCH_PATHS`` in order and returns the
    first existing executable path, or ``None`` if no converter is found.

    Args:
        extension: Lowercase file extension without dot (e.g. ``"rvt"``).

    Returns:
        Path to the converter executable, or ``None``.
    """
    exe_name = CONVERTERS.get(extension)
    if not exe_name:
        return None

    # Also check OPENESTIMATOR_CONVERTERS_DIR env var
    env_dir = os.environ.get("OPENESTIMATOR_CONVERTERS_DIR")
    search_paths = list(CONVERTER_SEARCH_PATHS)
    if env_dir:
        search_paths.insert(0, Path(env_dir))

    for search_path in search_paths:
        exe_path = search_path / exe_name
        if exe_path.exists():
            return exe_path

    return None


def is_cad_file(filename: str) -> bool:
    """Check if a filename has a supported CAD/BIM extension.

    Args:
        filename: File name or path (e.g. ``"project.rvt"``).

    Returns:
        ``True`` if the extension is supported.
    """
    ext = filename.rsplit(".", 1)[-1].lower() if "." in filename else ""
    return ext in SUPPORTED_CAD_EXTENSIONS


async def convert_cad_to_excel(
    input_path: Path,
    output_dir: Path,
    extension: str,
) -> Path | None:
    """Run a DDC converter to transform a CAD file into Excel.

    The converter is executed as a subprocess with a 5-minute timeout.

    Args:
        input_path: Path to the uploaded CAD file.
        output_dir: Directory where the Excel output should be written.
        extension: Lowercase file extension without dot.

    Returns:
        Path to the generated Excel file, or ``None`` on failure.
    """
    converter = find_converter(extension)
    if not converter:
        logger.error("No converter found for .%s", extension)
        return None

    logger.info("Converting %s using %s", input_path.name, converter.name)

    try:
        process = await asyncio.create_subprocess_exec(
            str(converter),
            str(input_path),
            "-o",
            str(output_dir),
            "--format",
            "excel",
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await asyncio.wait_for(
            process.communicate(),
            timeout=300,  # 5 min max
        )

        if process.returncode != 0:
            logger.error(
                "Converter failed (exit %d): %s",
                process.returncode,
                stderr.decode(errors="replace"),
            )
            return None

        # Find the generated Excel file in the output directory
        for f in output_dir.iterdir():
            if f.suffix in (".xlsx", ".xls"):
                return f

        logger.error("No Excel output found in %s after conversion", output_dir)
        return None

    except asyncio.TimeoutError:
        logger.error("Converter timed out after 300s for %s", input_path.name)
        return None
    except Exception:
        logger.exception("Converter error for %s", input_path.name)
        return None


def parse_cad_excel(excel_path: Path) -> list[dict]:
    """Parse the Excel output produced by a DDC converter.

    DDC converters produce Excel files with columns such as:
    Category, Family, Type Name, Count, Volume, Area, Length, Material, etc.

    Args:
        excel_path: Path to the Excel file generated by the converter.

    Returns:
        List of dicts where each dict represents one element row.
    """
    import openpyxl

    wb = openpyxl.load_workbook(excel_path, read_only=True, data_only=True)
    ws = wb.active

    if ws is None:
        wb.close()
        return []

    rows = list(ws.iter_rows(values_only=True))
    if not rows:
        wb.close()
        return []

    # First row is the header
    headers = [str(h or "").strip().lower() for h in rows[0]]

    elements: list[dict] = []
    for row in rows[1:]:
        if not any(row):
            continue

        item: dict = {}
        for i, header in enumerate(headers):
            if i < len(row):
                val = row[i]
                if val is not None:
                    item[header] = val

        if item:
            elements.append(item)

    wb.close()
    return elements


def summarize_cad_elements(elements: list[dict]) -> str:
    """Create a text summary of CAD elements suitable for AI processing.

    The summary is a tabular representation of element categories, types,
    counts, volumes, and areas. Limited to 200 elements to stay within
    AI context window limits.

    Args:
        elements: List of element dicts from ``parse_cad_excel``.

    Returns:
        Human-readable text summary of the CAD model contents.
    """
    if not elements:
        return "No elements found in the CAD file."

    lines = [f"CAD/BIM file contains {len(elements)} elements:\n"]
    lines.append("Category | Type | Count | Volume (m3) | Area (m2)")
    lines.append("-" * 60)

    for el in elements[:200]:  # Limit to 200 elements for AI context
        category = el.get("category", el.get("element type", "unknown"))
        type_name = el.get("type name", el.get("family", el.get("type", "")))
        count = el.get("count", 1)
        volume = el.get("volume", el.get("volume (m3)", ""))
        area = el.get("area", el.get("area (m2)", ""))

        lines.append(f"{category} | {type_name} | {count} | {volume} | {area}")

    if len(elements) > 200:
        lines.append(f"\n... and {len(elements) - 200} more elements (truncated)")

    return "\n".join(lines)


def _to_float(val: object) -> float:
    """Safely convert a value to float, returning 0.0 on failure."""
    if val is None:
        return 0.0
    try:
        return float(val)
    except (ValueError, TypeError):
        return 0.0


def group_cad_elements(elements: list[dict]) -> dict:
    """Group CAD elements by category and type, summing numeric quantities.

    Produces a structured dict of quantity tables suitable for direct display
    without AI processing. Each category contains type-level rows with summed
    count, volume (m3), area (m2), and length (m).

    Handles DDC column name variations:
    - ``category`` / ``element type`` -> category
    - ``type name`` / ``family`` / ``type`` -> type
    - ``volume`` / ``volume (m3)`` -> volume
    - ``area`` / ``area (m2)`` -> area
    - ``count`` defaults to 1

    Args:
        elements: List of element dicts from ``parse_cad_excel``.

    Returns:
        Dict with ``groups`` (list), ``grand_totals``, and ``total_elements``.
    """
    from collections import OrderedDict

    # category -> type -> aggregated values
    cat_types: dict[str, dict[str, dict]] = OrderedDict()

    for el in elements:
        category = str(
            el.get("category", el.get("element type", "Other"))
        ).strip() or "Other"
        type_name = str(
            el.get("type name", el.get("family", el.get("type", "Unknown")))
        ).strip() or "Unknown"
        count = _to_float(el.get("count", 1))
        volume = _to_float(el.get("volume", el.get("volume (m3)", 0)))
        area = _to_float(el.get("area", el.get("area (m2)", 0)))
        length = _to_float(el.get("length", 0))
        material = str(el.get("material", "")).strip()

        if category not in cat_types:
            cat_types[category] = OrderedDict()

        if type_name not in cat_types[category]:
            cat_types[category][type_name] = {
                "type": type_name,
                "material": "",
                "count": 0.0,
                "volume_m3": 0.0,
                "area_m2": 0.0,
                "length_m": 0.0,
            }

        entry = cat_types[category][type_name]
        entry["count"] += count
        entry["volume_m3"] += volume
        entry["area_m2"] += area
        entry["length_m"] += length
        if material and not entry["material"]:
            entry["material"] = material

    # Build structured output
    groups: list[dict] = []
    grand_count = 0.0
    grand_volume = 0.0
    grand_area = 0.0
    grand_length = 0.0

    for cat_name, types in cat_types.items():
        items = list(types.values())

        cat_count = sum(it["count"] for it in items)
        cat_volume = sum(it["volume_m3"] for it in items)
        cat_area = sum(it["area_m2"] for it in items)
        cat_length = sum(it["length_m"] for it in items)

        # Round item values
        for it in items:
            it["count"] = round(it["count"], 1)
            it["volume_m3"] = round(it["volume_m3"], 3)
            it["area_m2"] = round(it["area_m2"], 2)
            it["length_m"] = round(it["length_m"], 2)

        groups.append({
            "category": cat_name,
            "items": items,
            "totals": {
                "count": round(cat_count, 1),
                "volume_m3": round(cat_volume, 3),
                "area_m2": round(cat_area, 2),
                "length_m": round(cat_length, 2),
            },
        })

        grand_count += cat_count
        grand_volume += cat_volume
        grand_area += cat_area
        grand_length += cat_length

    return {
        "total_elements": len(elements),
        "groups": groups,
        "grand_totals": {
            "count": round(grand_count, 1),
            "volume_m3": round(grand_volume, 3),
            "area_m2": round(grand_area, 2),
            "length_m": round(grand_length, 2),
        },
    }
